#!/bin/bash

#uses ImageMagick
for filename in `find . -regex ".*.svg"`; do
convert -background none $filename -filter triangle -interpolative-resize 16x16! -blur 0x.3 -raise 1 thumbnail.png;
convert thumbnail.png -fill gray50 -colorize 100% -raise 1 -normalize -blur 0x4 overlay.png;
convert thumbnail.png overlay.png -compose hardlight -composite ${filename%svg}png;
done
rm thumbnail.png overlay.png;

mkdir crush16
for filename in `find . -regex ".*.png"`; do
pngcrush -rem alla -rem text $filename crush16/${filename:2}
done

rm *.png;